### ISSUE TITLE
Control Power state

### ISSUE THREAD

**Issue by Nicoautoxp** [Sholofly/lghorizon#177]
Hi, 
I can't remember but was there not a way to control the powerstate of the TV-box via the integration? 
I tried to call it via an automation and a script but It doesn't seem possible to control the power state.

![Image](https://github.com/user-attachments/assets/4d4d4706-a0df-4d0d-a00d-1ba64b67b10b)

**Comment by grewhit25** [comment]
@Nicoautoxp If you’re referring to powering on your TV box, here’s how I do it on my Virgin TV360 box:
Note: ‘Power’ is uppercase ‘P’.
I also had to change the power standby state to ‘fast start’ in the Virgin TV360 settings.

``` yaml
# Turn on Virgin TV360 Box using lghorizon integration
- action: lghorizon.remote_key_press
  data:
    entity_id: "{{ virgin_tv_360 }}"
    remote_key: 'Power'
```
