### ISSUE TITLE
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3

### ISSUE THREAD

**Issue by marcokreeft87** [Sholofly/lghorizon#56]
**Describe the bug**
HA shows in log:

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for lghorizon using this method at custom_components/lghorizon/__init__.py, line 49: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**To Reproduce**
Upgrade HA to version greater than 2023.3.
Start HA and check log

**Expected behavior**
No error in log

**Version of the component**
0109318

**Logging**
NA

**Additional context**
```yaml
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 15:59:20 (1 occurrences)
Last logged: 15:59:20

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for lghorizon using this method at custom_components/lghorizon/__init__.py, line 49: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
```
