### ISSUE TITLE
lghorizon.remote_key_press doesn't work anymore

### ISSUE THREAD

**Issue by 1aranzant** [Sholofly/lghorizon#74]
Since a few weeks, sending commands through the LG Horizon: Send key doesn't do anything anymore. 

The commands used to work, such as the following, but since then doesn't do anything... even though it returns ""Action run succesfully""

`entity_id: media_player.telenet_tv_box
remote_key: ChannelDown`

What coud be the issue? 

I am using Telenet in Belgium. 
(I can still change channels from the media player entity).

**Comment by Sholofly** [comment]
Sorry, the docs are a little off: Have you tried:

```yaml
service: lghorizon.remote_key_press
data:
  entity_id: media_player.telenet_tv_box
  remote_key: ChannelDown
```
