### ISSUE TITLE
Browse media directly from media card / buttons for favourite channels

### ISSUE THREAD

**Issue by pjannink** [Sholofly/lghorizon#89]
I would like to be able to browse media directly from the card. Now I have to push the 3 dots in the upper right corner and browse the channels on the next dialog window.
Further: I would like to create a series of buttons to directly jump to my favourite channels. How to do that?

Thx for your help!

**Comment by Sholofly** [comment]
> I would like to be able to browse media directly from the card. Now I have to push the 3 dots in the upper right corner and browse the channels on the next dialog window.

By choosing a card that supports it like: https://github.com/kalkih/mini-media-player

> Further: I would like to create a series of buttons to directly jump to my favourite channels. How to do that?

By reading the docs :). Create buttons with an action attached:
```yaml
service: media_player.play_media
data:
  media_content_type: channel # 'channel' when media_content_id is channelnumber, 'app' when media_content_id is 'Netflix' or 'Videoland'
  media_content_id: "401" # Any channel number, 'Netflix' or 'Videoland'
target:
  entity_id: media_player.ziggo_beneden
```
